# Generated by Django 3.2.5 on 2021-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
